"""Innitial migration.

Revision ID: 1c75db0d68ca
Revises: 
Create Date: 2024-01-15 22:07:56.466174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c75db0d68ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_inventory',
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('Make', sa.String(length=100), nullable=False),
    sa.Column('Model', sa.String(length=100), nullable=False),
    sa.Column('Year', sa.Integer(), nullable=True),
    sa.Column('SerialNumber', sa.String(length=100), nullable=False),
    sa.Column('Purpose', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('img', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('machine_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device_inventory')
    # ### end Alembic commands ###
