""" Complete New migration.

Revision ID: 8df72737a0c8
Revises: f8670924c3ca
Create Date: 2024-01-16 01:58:51.133772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8df72737a0c8'
down_revision = 'f8670924c3ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    '''op.create_table('DeviceInventory',
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('Make', sa.String(length=100), nullable=False),
    sa.Column('Model', sa.String(length=100), nullable=False),
    sa.Column('Year', sa.Integer(), nullable=True),
    sa.Column('SerialNumber', sa.String(length=100), nullable=False),
    sa.Column('Purpose', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('img', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('machine_id'),
    schema='r-schema-01'
    )'''
    op.create_table('Employees',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('FirstName', sa.String(length=100), nullable=False),
    sa.Column('LastName', sa.String(length=100), nullable=False),
    sa.Column('Birthdate', sa.Date(), nullable=True),
    sa.Column('JobTitle', sa.String(length=100), nullable=False),
    sa.Column('UserName', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('pwhash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('employee_id'),
    sa.UniqueConstraint('UserName'),
    sa.UniqueConstraint('email'),
    schema='r-schema-01'
    )
    op.create_table('Metrics',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=True),
    sa.Column('Value1', sa.String(length=100), nullable=False),
    sa.Column('Value2', sa.String(length=100), nullable=False),
    sa.Column('Value3', sa.String(length=100), nullable=False),
    sa.Column('Value4', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('EmpID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['EmpID'], ['r-schema-01.Employees.employee_id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['r-schema-01.DeviceInventory.machine_id'], ),
    sa.PrimaryKeyConstraint('item_id'),
    schema='r-schema-01'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Metrics', schema='r-schema-01')
    op.drop_table('Employees', schema='r-schema-01')
    op.drop_table('DeviceInventory', schema='r-schema-01')
    # ### end Alembic commands ###
