""" New Table migration.

Revision ID: f8670924c3ca
Revises: c8fc314e2790
Create Date: 2024-01-16 00:56:11.208395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8670924c3ca'
down_revision = 'c8fc314e2790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    '''op.create_table('DeviceInventory',
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('Make', sa.String(length=100), nullable=False),
    sa.Column('Model', sa.String(length=100), nullable=False),
    sa.Column('Year', sa.Integer(), nullable=True),
    sa.Column('SerialNumber', sa.String(length=100), nullable=False),
    sa.Column('Purpose', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('img', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('machine_id'),
    schema='r-schema-01'
    )'''
    # ### end Alembic commands ###


#def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('DeviceInventory', schema='r-schema-01')
    # ### end Alembic commands ###
